package kz.iitu.mastermind.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;

@Data
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "user"})
@ApiModel(value = "Game model")
public class Game {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ApiModelProperty(value = "Secret code generated by computer")
    private int secretNumber;
    @ApiModelProperty(value = "Number of attempts made by user to guess the code")
    private int numberOfGuesses;
    @ApiModelProperty(value = "The game was lost or won")
    private boolean win;
    @ApiModelProperty(value = "The number of points received per game")
    private int score;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", updatable = false)
    private User user;

}
